all:
	gcc -Wall -g -std=c99 -Werror forkloop.c -o forkloop
	gcc -Wall -g -std=c99 -Werror fork_1.c -o fork_1
	gcc -Wall -g -std=c99 -Werror fork_2.c -o fork_2
	gcc -Wall -g -std=c99 -Werror fork_3.c -o fork_3
	gcc -Wall -g -std=c99 -Werror fork_4.c -o fork_4
clean:
	rm -f forkloop fork_1 fork_2 fork_3 fork_4
